snowflake:
  account: "WB19670-C2GPARTNERS"
  user: "xxx@xxx.COM"
  authenticator: "externalbrowser"
  database: "SANDBOX"
  schema: "DS"

databricks:
  server_hostname: "xx-xxxx.cloud.databricks.com"
  http_path: "/sql/1.0/warehouses/xxxxx"
  access_token: "xxxxx"
  database: "nbcu_demo"

validation:
  unique_columns:
    nbcu_customers: "customer_id"
    NBCU_DEPARTMENTS: "department_id"
    NBCU_EMPLOYEES: "employee_id"
    NBCU_PRODUCTS: "product_id"
    NBCU_PROJECTS: "project_id"
    NBCU_SALES: "sale_id"
    NBCU_SUPPLIERS: "supplier_id"
    NBCU_SUPPLY_CHAIN: "supply_chain_id"


